### ISSUE TITLE
Add duplicate PR detection

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-github-triage-actions#114]
It is possible that if you toggle from draft, ready for review, back to draft that the message is posted twice. It is also possible someone manually posts a message prior to the the bot getting to it. We should detect duplicates and not post.

A large part of these issues stem from PRs being converted to draft very close to creation time but the GitHub payload still comes back as draft

**Comment by joaomoreno** [comment]
cc @joaomoreno

**Comment by lramos15** [comment]
@joaomoreno The PR that went in is to prevent the overzealous draft posting. If we still see duplicate PRs that aren't caused by the draft bug being posted I can implement full duplicate detection
