### ISSUE TITLE
Search issues are only assigned to me and not Andrea

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-github-triage-actions#119]
Here's a new example: https://github.com/microsoft/vscode/issues/162436

I've registered her and I both for search issues in our classifier.json

**Comment by lramos15** [comment]
Thanks, I will try to retrain the model during debt week as I do think it's a bit unhealthy as well

**Comment by lramos15** [comment]
Optimistically closing as I believe Andrea is being properly assigned.
