### ISSUE TITLE
"old version" should support `main` or commit hash

### ISSUE THREAD

**Issue by mrienstra** [microsoft/vscode-github-triage-actions#121]
Continuation of https://github.com/microsoft/vscode-github-triage-actions/pull/72 & https://github.com/microsoft/vscode-github-triage-actions/issues/61.

I just opened https://github.com/microsoft/vscode/issues/162609 & triggered "you may be using an old version", based on this line:

>- VS Code Version: `main` (currently at [`2a07191`](https://github.com/microsoft/vscode/commit/2a07191997b27d7f28b83de7099bf46e70f5f24c))

I'm not suggesting that the exact syntax I used should be supported, but it would be nice to try to support `main` and/or a GitHub commit hash in some way or another. And by "support", I mean: don't suggest upgrading to the latest version.

**Comment by lramos15** [comment]
99% of the time this section is filled out it is filled out by the issue reporter built into VS Code. I would argue that your bug you filed and linked wasn't against any VS code version at all and instead was just against our engineering repo setup. I guess a possible enhancement we could do here is ignore versions not in the x.x.x format

**Comment by mrienstra** [comment]
That sounds great. Granted, not worthwhile unless it can be done very quickly, as it won't affect very many people.

**Comment by lramos15** [comment]
Closing as out of scope as we don't plan to address this in the near future since it doesn't affect 99% of users. If you want to try and implement a fix for this then feel free 👍
