### ISSUE TITLE
PR chat bot failing in vscode-autopep8

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-github-triage-actions#129]
Repo: https://github.com/microsoft/vscode-autopep8  

[logs](https://github.com/microsoft/vscode-autopep8/actions/runs/3325526840/jobs/5498303326)

**Comment by karthiknadig** [comment]
It seems to occasionally fail here as well: https://github.com/microsoft/vscode-python/actions/runs/3333228175/jobs/5514960457

**Comment by karthiknadig** [comment]
@lramos15 This still seems to be failing: https://github.com/microsoft/vscode-autopep8/actions/runs/3371847554/jobs/5594580219

**Comment by lramos15** [comment]
Oh, it's because this repo was never on boarded to the chat bot. Someone placed the .YML file in, but that's not enough. It actually needs to be added to the secret application toolings. This must've never worked

**Comment by lramos15** [comment]
Secret should be added and now working
