### ISSUE TITLE
hola 

### ISSUE THREAD

**Issue by JuanfPuebla** [microsoft/vscode-github-triage-actions#14]
// Lectura de su valor.
char x = arrayCaracteres[2];

// Asignación de un valor. Como se puede comprobar se pone el  número dos, que coincide con el tercer elemento. Ya que como  dijimos anteriormente el primer elemento es el cero.
arrayCaracteres[2] = 'b';

**Comment by JacksonKearl** [comment]
helo, 

Closing out as I don't think this issue is relevant to this repository.
