### ISSUE TITLE
Use /files for codereview links

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-github-triage-actions#155]
The codereview bot links to PRs like this:
https://github.com/microsoft/vscode-tools/pull/189
Can we make that
https://github.com/microsoft/vscode-tools/pull/189/files
?
Would save a click

**Comment by lramos15** [comment]
I personally enjoy reading the description of the PRs before reviewing them so I have context.

**Comment by lramos15** [comment]
Closing as out of scope since this is personal preference
