### ISSUE TITLE
Test plan item marked as invalid even though it is not

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-github-triage-actions#190]
- Sample valid TPI -  https://github.com/microsoft/vscode-internalbacklog/issues/4693 
- Open it and label as test-planitem

🐛 BOT invalidates it because the ref issue is not found even though it exists.

CC @lszomoru

**Comment by lszomoru** [comment]
I believe that this will happen to **all** TPIs that are created in vscode-internalbacklog that reference an issue in vscode.
