### ISSUE TITLE
The bot assigned me an old, closed issue

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-github-triage-actions#27]
https://github.com/microsoft/vscode/issues/44518#event-4865749716

The bot just assigned me this old issue that was closed 2 years ago (possibly because Rachel is no longer on the team?)

**Comment by JacksonKearl** [comment]
Hah... it was trying to assign you to https://github.com/microsoft/vscode/issues/125847, but that got redirected to https://github.com/microsoft/TypeScript/issues/44518, so it actually assigned you to https://github.com/microsoft/vscode/issues/44518

**Comment by fatcerberus** [comment]
Guess the robot apocalypse isn't happening anytime soon.  The *zombie* apocalypse, on the other hand...
