### ISSUE TITLE
Improving the Description

### ISSUE THREAD

**Issue by cihanisma** [microsoft/vscode-github-triage-actions#30]
Current:
- There is an ambiguous point about the description written by vscode-triage-bot
- It's not clear if vscode-triage-bot counts all the votes in the feature-suggestion comments or only the first post
- Example https://github.com/microsoft/vscode/issues/127087#issuecomment-867693902

Update:
- Writing a description that will not leave any ambiguity

**Comment by JacksonKearl** [comment]
This issue text has a link in the word "upvote" to this wiki page: https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request. IMO that page is pretty clear, let me know if you have feedback on it.

**Comment by cihanisma** [comment]
The sentence on the description page and the picture under it are creating confusion again. In the example picture, making the request over the bot account and casting the vote for it, leaves the user in a dilemma.

Also it's pointless for a user to need secondary page redirection for a very simple function description. By adding just one sentence, it can be clarified where it should be upvoted. It can be seen on the sample request I sent that the current description is clear to you but not to users. Thanks for your understanding.

**Comment by JacksonKearl** [comment]
Happy to hear any proposals for new text.

**Comment by cihanisma** [comment]
I think updating this will suffice:
> The community has 60 days to upvote the issue.

as

`The community has 60 days to upvote the request above.`

Thanks.

**Comment by cihanisma** [comment]
> Happy to hear any proposals for new text.

@JacksonKearl As I can see, some users are still voting for the bot's description. This means that updating the description as above would be really helpful.

**Comment by cihanisma** [comment]
Or, considering this situation, upvotes given to the bot should be added while counting the votes.
