### ISSUE TITLE
The triage bot is reposting spam

### ISSUE THREAD

**Issue by DecimalTurn** [microsoft/vscode-github-triage-actions#315]
It seems that the bot is repositing spam as issues over here: https://github.com/VSCodeTriageBot/testissues/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

Is that intentional? I found this while searching on GitHub for the presence of spam/malware and was suprised to see this content posted by a trusted bot.

![image](https://github.com/user-attachments/assets/748daed5-44a1-4855-bd08-d03edab6022d)

**Comment by lramos15** [comment]
This should be fixed now. The bot would just replicate what was posted in VS Code for AI training purposes.
