### ISSUE TITLE
Why there is no more automated duplicate issue detection?

### ISSUE THREAD

**Issue by happygirlzt** [microsoft/vscode-github-triage-actions#42]
Hi there, I noticed that there are two types of bots used in the vscode repo, i.e., `vscodebot` and `vscode triage bot`. It seems `vscodebot` is not active anymore. I just checked this repo and it seems there is no duplicate issue detection function (e.g., https://github.com/microsoft/vscode/issues/131696#issuecomment-906144048) implemented. I am just curious why it is the case. Thank you for your time if you are willing to talk about it a bit :)

**Comment by JacksonKearl** [comment]
The duplicate detection bot was running on a dedicated server rather than GHA. I am not sure what the current status of that server is. (cc @chrmarti)
