### ISSUE TITLE
Label issues that were filed for an old version of vscode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-github-triage-actions#61]
I sometimes don't notice when the vscode version on an issue is out of date. It would be helpful to get a label or a comment on issues that are not on the latest version.

**Comment by gjsjohnmurray** [comment]
@JacksonKearl I wonder why https://github.com/microsoft/vscode/issues/149804 triggered this.

**Comment by JacksonKearl** [comment]
it was edited, original was:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/8586769/169144024-1bf0fb0b-de07-4f5d-a954-c29e855b374a.png">

**Comment by gjsjohnmurray** [comment]
@JacksonKearl how about microsoft/vscode#149987? Is the "(Universal)" suffix confusing the bot?

**Comment by JacksonKearl** [comment]
Good catch, there it's from the duplicate "Version" and being on separate lines:
```
VS Code Version:
Version: 1.67.2 (Universal)
```

https://github.com/microsoft/vscode-github-triage-actions/pull/69 should fix

**Comment by jfunmaker** [comment]
Sj wonder why
