### ISSUE TITLE
Set `not planned` as the `state_reason` when automatically closing issues

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-github-triage-actions#82]
The underlying octokit API (the latest version) has added a `state_reason` for specifying GitHub's new closing state.  (It's not entirely clear to me if the correct value would be `not planned` or `not-planned`).

[The new GitHub Issues - May 19th update | GitHub Changelog](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/)

Opening this issue to track updating VS Code's actions to specify the `state_reason` when automatically closing issues.

We cloned the VS Code actions as the basis for actions in the vscode-cpptools repo.  Since using the latest octokit seems to require updating other dependencies, I figured I'd wait for you guys to address this first, then ingest your changes.  :)

**Comment by lramos15** [comment]
The comamnds.json now accepts a "reason" entry which is either "complete"d or "not_planned". It will default to completed just because that was the default behavior before
