### ISSUE TITLE
Bot to post who the new build champ is?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-github-triage-actions#83]
Currently the build champ role can get forgotten and relies on my checking the ✅ emojis in #build against https://github.com/microsoft/vscode-internalbacklog/blob/main/assignments/build-champs.md to make sure everything is working correctly. It'd be nice if the ping happened automatically.

**Comment by joyceerhl** [comment]
A low-hanging alternative is to have the Slackbot post a reminder to handoff the build champ role, similar to what we do for twitter tracking.

**Comment by lramos15** [comment]
Slackbot is currently being used, will close this for now. If we get an API that isn't just scanning the internal backlog then this can be done better but right now the info is very fragmented.
